### ISSUE TITLE
Show parent items

### ISSUE THREAD

**Issue by oskarrough** [jessaustin/gulp-nav#4]
Hi, thank you for this plugin. On the following page the 1st level nav isn't shown since it's not the direct parent anymore. How would you make it keep level 1 visible? E.g. one, latin, two, three, greek.

http://jessaustin.github.io/gulp-nav/latin/letter-a.html

**Comment by jessaustin** [comment]
The template determines what is displayed. If you look at [the code](https://github.com/jessaustin/gulp-nav/blob/master/test/index.jade#L13-L17), you'll see we're referring to `nav.parent`. You can also use `nav.parent.parent`, `nav.parent.parent.parent`, etc. Of course, if you go far enough, there won't *be* another level of parents. That's why the template should also check whether the parent exists, like this template does; there is no "Up" link at the [top level](http://jessaustin.github.io/gulp-nav/).

Similarly, all items in `nav.children` will themselves have `children` properties, although of course any particular `children` array may be empty.

**Comment by oskarrough** [comment]
Cheers, works just fine!

**Comment by jessaustin** [comment]
Glad to hear it, @oskarrough! :smile:
